# Generated by Django 5.2.6 on 2025-09-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('target_audience', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('certificate_provided', models.BooleanField(default=False)),
                ('interests_aligned', models.TextField(help_text='List interests, one per line.')),
            ],
        ),
    ]
